#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol before
# apcupsd kills the power in the UPS. You probably
# need to edit this to mount read-only /usr and /var,
# otherwise apcupsd will not run.

# Customized by Charles-Emmanuel CAMUS (github.com/miniche)

# From (one mail address)
FROM_MAIL='your.mail@host.com'
# To : you can add more than one address. They must be separated by a space
TO_MAIL='your.mail@host.com'

APCUPSD_MAIL="/usr/sbin/sendmail"

HOSTNAME=`hostname`
MSG="$HOSTNAME - Battery low : UPS will shutdown power"
LEFT=`/sbin/apcaccess status | grep TIMELEFT | awk 'BEGIN { FS=":" } END { print $2 }'`

#
(
    echo "From: $FROM_MAIL"
    echo "Subject: $MSG"
    echo " "
    echo "$MSG"
    echo " "
    echo "Time left on battery : $LEFT"
    echo " "
    echo " "
    /sbin/apcaccess status
) | $APCUPSD_MAIL -s "$MSG" $TO_MAIL
exit 0

exit 0
